package presenter;

public enum Controllers {
    LEAVE_REQUEST,
    SALARY_CALCULATOR,
    CREATE_TASK,
    ENROLL_EMPLOYEE,
    CREATE_PROJECT,
    COMPLETE_TASK,
    COMPLETE_PROJECT,
    EXAMPLE_USE_CASE, EVALUATE_TASK, APPROVE_LEAVE_TASK,

}
